# Generated by Django 3.0.8 on 2020-07-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
